### PR TITLE
Handled coming back to a filtered GridField

### PR DESCRIPTION
**Pull request by g4b0**
Js code from https://github.com/silverstripe/silverstripe-framework/issues/3229#issuecomment-224785229

Also have a look to https://github.com/unclecheese/silverstripe-gridfield-betterbuttons/issues/45#issuecomment-295775107

### CODE REVIEW

**Comment by stevie-mayhew** [comment]
Thanks @g4b0 !

**Comment by g4b0** [comment]
Thanks to you for merging @stevie-mayhew

**Comment by bscarola** [comment]
I just tested this w/ a fresh SilverStripe 3.6 install and it does not appear to be working because the 'ss-gridfield' dom element is not present on the item edit form page. I changed the DOM selector on line 3: $('.ss-gridfield') to $('.cms-edit-form') and it's working.

**Comment by stevie-mayhew** [comment]
@bscarola would you be able to put together a PR for this? If you can change the requirements in `composer.json` to have at least version 3.6.0 of SS as well that would be great!

**Pull request merged**
